let suggestion=[
    'Hello',
    'Word',
    'Book',
    'Water',
    'JavaScript',
    'HTML',
    'Css',
    'Learn Css',
    'Learn HTML',
    'Learn Js',
    'Learn React js',
    'simulation',
    'Responsive sites',
    'Responsive',
    'Youtube',
    'Youtuber',
    'Youtube Channel',
    'Channel',
    'Facebook',
    'Freelancer',
    'Telegram',
    'Whatsapp',
    'Vlive',
    'Weverse',
    'Github',
    'Git',
    'Linkedin'
]